
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T14:11:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7139b94b078c7a48eb21d258f0f65c67bfeeaac5",
 "version": "21.10.00a+33.g7139b94"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
