[tool.poetry]
authors = ["ldsands <ldsands@outlook.com>"]
classifiers = [
  "License :: OSI Approved :: MIT License",
]
description = "Functions I use regularly with my python projects"
license = "MIT License"
name = "SandsPythonFunctions"
packages = [
  {include = "SandsPythonFunctions", from = "src"},
]
readme = "README.md"
repository = "https://github.com/ldsands/SandsPythonFunctions"
version = "0.1.0"

[tool.poetry.dependencies]
#python
python = ">=3.9,<3.11"
# packages used for general python purposes
wheel = "^0.37.0"
# packages that aren't strictly needed but I always install them anyway so I decided to add them here
black = "^20.8b1"
flake8 = "^3.8.4"
pretty-errors = "^1.2.24"
isort = "^5.7.0"
# data file management and manipulation
numpy = "^1.21.2"
pandas = "^1.3.3"
pyarrow = "^5.0.0"
zstandard = "^0.15.1"
vaex = "^4.5.0"
openpyxl = "^3.0.7"


[tool.poetry.dev-dependencies]
# here you put any packages that would be used in development of the package such as packages used in testing

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=1.1.9"]
