# @package _group_
_target_: pytorch.recipes.data.modules.vision.classy_fb_data_module.ClassyFbDataModule
dataset:
  train:
    name: imagenet
    split: train
    batchsize_per_replica: 32
    num_samples: 1281167
    phases_per_epoch: 1
    use_shuffle: true
    num_threads: 2
    transforms:
    - name: image_decode_index
      config:
        color_space: RGB
        num_classes: 1000
        single_label: true
      transforms:
      - name: RandomResizedCrop
        size: 224
      - name: RandomHorizontalFlip
      - name: ToTensor
      - name: Normalize
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
  val:
    name: imagenet
    split: test
    batchsize_per_replica: 32
    num_samples: 50000
    use_shuffle: false
    num_threads: 2
    transforms:
    - name: image_decode_index
      config:
        color_space: RGB
        num_classes: 1000
        single_label: true
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean:
          - 0.485
          - 0.456
          - 0.406
          std:
          - 0.229
          - 0.224
          - 0.225
  test:
    name: imagenet
    split: test
    batchsize_per_replica: 32
    num_samples: 50000
    use_shuffle: false
    num_threads: 2
    transforms:
    - name: image_decode_index
      config:
        color_space: RGB
        num_classes: 1000
        single_label: true
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean:
          - 0.485
          - 0.456
          - 0.406
          std:
          - 0.229
          - 0.224
          - 0.225
