# @package _group_
_target_: pytorch.recipes.data.modules.vision.classy_fb_data_module.ClassyFbDataModule
dataset:
  train:
    name: synthetic_image
    crop_size: 224
    class_ratio: 0.5
    num_samples: 100
    seed: 0
    batchsize_per_replica: 20
    use_shuffle: false
    transforms:
      - name: apply_transform_to_key
        transforms:
          - name: ToTensor
          - name: Normalize
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        key: input
    num_workers: 1
  val:
    name: synthetic_image
    crop_size: 224
    class_ratio: 0.5
    num_samples: 100
    seed: 1
    batchsize_per_replica: 20
    use_shuffle: false
    transforms:
      - name: apply_transform_to_key
        transforms:
          - name: ToTensor
          - name: Normalize
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        key: input
    num_workers: 1
  test:
    name: synthetic_image
    crop_size: 224
    class_ratio: 0.5
    num_samples: 100
    seed: 2
    batchsize_per_replica: 20
    use_shuffle: false
    transforms:
      - name: apply_transform_to_key
        transforms:
          - name: ToTensor
          - name: Normalize
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        key: input
    num_workers: 1
