
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: envoy.docs.sphinx_runner:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'classifiers': """
Development Status :: 4 - Beta
Framework :: Pytest
Intended Audience :: Developers
Topic :: Software Development :: Testing
Programming Language :: Python
Programming Language :: Python :: 3
Programming Language :: Python :: 3.8
Programming Language :: Python :: 3.9
Programming Language :: Python :: 3 :: Only
Programming Language :: Python :: Implementation :: CPython
Operating System :: OS Independent
License :: OSI Approved :: Apache Software License""",
    'description': '"Sphinx docs builder used in Envoy proxy\'s CI"',
    'entry_points': {
        'console_scripts': [
            'envoy.docs.sphinx_runner=envoy.docs.sphinx_runner:cmd',
        ],
    },
    'license': 'Apache Software License 2.0',
    'long_description': 'file: README.rst',
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'envoy.docs.sphinx_runner',
    'url': 'https://github.com/envoyproxy/pytooling/tree/main/envoy.docs.sphinx_runner',
    'version': '0.0.1',
    'package_dir': {
        '': 'src',
    },
    'packages': (
        'envoy.docs.sphinx_runner',
    ),
    'namespace_packages': (
    ),
    'package_data': {
        'envoy.docs.sphinx_runner': (
            'py.typed',
        ),
    },
    'install_requires': (
        'colorama',
        'envoy.base.runner>=0.0.4',
        'envoy.base.utils>=0.0.8',
        'sphinx',
        'sphinx-copybutton',
        'sphinx-rtd-theme',
        'sphinx-tabs',
        'sphinxcontrib-httpdomain',
        'sphinxcontrib-serializinghtml',
        'sphinxext-rediraffe',
    ),
})
