[tool.poetry]
name = "indianapy"
version = "0.1.0"
description = "Enforces the  Indiana Pi Bill"
authors = ["Michaela <git@michaela.lgbt>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
