[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] (%(filename)s:%(lineno)s) %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
addopts = "--flake-finder --flake-runs=1 --reruns 0 --reruns-delay 1"


[tool.poetry]
name = "able"
version = "0.3.1"
description = "Able stands for Allthenticate's Bluetooth Low Energy (Library) and serves to be a platform agnostic python library for communication with centrals as a BLE Peripheral."
authors = ["Bernie Conrad <bernie@allthenticate.net>", "Allthenticate help@allthenticate.net"]
repository = "https://gitlab.com/allthenticate/software/able"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
dbus-next = {version = "^0.2.2", markers = "sys_platform == 'linux'"}
pyobjc = {version = "^7.3", markers = "sys_platform	== 'darwin'"}

[tool.poetry.dev-dependencies]
black = "21.7b0"
pytest = "6.2.4"
coverage = "5.5"
pylint = "^2.9.6"
pytest-cov = "2.12.1"
pytest-asyncio = "^0.15.1"
bleak = "^0.12.1"
pre-commit = "^2.13.0"
Sphinx = "^4.1.1"
sphinx-rtd-theme = "^0.5.2"
mock = "^4.0.3"
pytest-rerunfailures = "^10.1"
pytest-flakefinder = "^1.0.0"
pytest-sugar = "^0.9.4"
pytest-fast-first = "^1.0.3"
furo = "^2021.7.5-beta.38"
pyserial = "^3.5"
hypothesis = "^6.14.3"
mypy = "^0.910"
aioconsole = "^0.3.1"
isort = "^5.9.3"
adb-shell = {extras = ["usb"], version = "^0.4.0"}
pydeps = "^1.9.14"
sphinx-copybutton = "^0.4.0"
sphinx-autodoc-annotation = "^1.0-1"
sphinx-autobuild = "^2021.3.14"
sphinx-autodoc-typehints = "^1.11.1"
coloredlogs = "^15.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
