[tool.poetry]
name = "evergreen-lint"
version = "0.1.4"  # Duplicated in the top-level __init__.py.
description = ""
authors = ["Richard Samuels <richard.samuels@mongodb.com>"]

[tool.poetry.scripts]
main = "evergreen_lint.__main__:main"

[tool.poetry.dependencies]
# Python version should be set to the minimum supported toolchain version
python = "^3.7"
# These dependencies are tied to whatever versions are used by the oldest
# supported branch of MongoDB server, presently 5.0
PyYAML = ">=3.0.0"
typing-extensions = "^3.10.0"
click = "~=7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "~=0.800"
flake8 = "^3.9.2"
flake8-bugbear = "^21.4.3"
isort = "^5.8.0"
black = "^21.5b2"
pytest-black = "^0.3.12"
pytest-flake8 = "^1.0.7"
pytest-mypy = "^0.8.1"
pytest-isort = "^2.0.0"

[tool.black]
line-length = 100
target-version = ['py37']

[tool.pytest.ini_options]
#flake8-ignore = "W605 W503 W291 E203 E501 F821"
flake8-ignore = "E501"
addopts = "--flake8 --black --mypy --isort"
testpaths = [
    "evergreen_lint",
    "tests",
]

[tool.isort]
profile="black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
