
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T13:19:35+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "904e8ec9af9168db65aaa9a9177ee6cfacf72c6b",
 "version": "0.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
