# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Build
on: [push, pull_request]

jobs:
  # https://github.com/pre-commit/action
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Enable rootless podman
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y fuse-overlayfs
          podman info
          slirp4netns --version
          fuse-overlayfs --version
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: actions/setup-node@v1
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install -r dev-requirements.txt
          npm install -g configurable-http-proxy
      - name: Update setuptools_scm version
        run: python setup.py build
      - name: Run tests
        run: pytest tests -v

  # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  publish-pypi:
    name: Pypi
    needs:
      # Only publish if other jobs passed
      - pre-commit
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install pypa/build
        run: python -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.3.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
