
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T11:40:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfe48dfa3542e083d73b51ca3cd21267cb3281a5",
 "version": "0.7.1.post.dev52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
