
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-16T13:21:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8caa2e78d71a4a49dd0c4175c328419b02c06e3b",
 "version": "0.13.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
