[tool.poetry]
name = "pornhub-api-client"
version = "0.1.5"
description = "Simple lib to work with pornhub API"
authors = ["Misha Bystrov <drudkhmisha@gmail.com>"]
packages = [
    { include = "pornhub"}
]

[tool.poetry.dependencies]
python = "^3.8"
requests2 = "^2.16.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
jsonschema = "^3.2.0"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
requests2 = "^2.16.0"
black = "^21.5b0"

[tool.poetry.scripts]
phb = "pornhub.client:main"
run-tests = "pornhub.tests.unit_test:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

