
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T14:04:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdd9cbfd111ae2389ccfea29005e2fc4fef17c12",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
