[tool.poetry]
name = "remote_event_bundle"
version = "2.1.0"
description = "Remote events"
authors = ["Alvaro Garcia <maxpowel@gmail.com>"]
license = "Apache"

[tool.poetry.dependencies]
python = "^3.6"
applauncher = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
