[tool.poetry]
name = "demasci"
version = "0.0.1"
description = "Decision Making Science Tools"
authors = ["James Davis <jamesmariodavis@gmail.com>"]

[tool.pytest.ini_options]
markers=[
    "external_deps: test requires internet connection and valid secrets",
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

# https://python-poetry.org/docs/dependency-specification/
[tool.poetry.dependencies]
python = ">=3.9, <3.10"
numpy = "^1.21.2"
pandas = "^1.3.2"

[tool.poetry.dev-dependencies]
yapf = "^0.31.0"
pylint = "^2.10.2"
mypy = "^0.910"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
pytest-xdist = "^2.3.0"