
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T11:53:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3bd9a85376a950de13608693fbb41fe668b45ff",
 "version": "2533"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
