
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-19T22:52:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "da61b0a12f194b856be08dbd10fb84047eda7d5c",
 "version": "0.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
