
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T10:14:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdeb547d33d115aa3e5a9feab1c0f0c065ed0738",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
