
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-20T14:04:48-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "050acfa21891200ab2177e659f61cebd92117ec5",
 "version": "v0.1.2-alpha"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
