#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['typeguard']

extras_require = \
{'doc': ['sphinx', 'sphinx_rtd_theme', 'autoclasstoc'],
 'test': ['pytest', 'pytest-cov', 'coveralls']}

setup(name='signature_dispatch',
      version='1.0.0',
      description='Execute the first function that matches the given arguments.',
      author='Kale Kundert',
      author_email='kale@thekunderts.net',
      url='https://github.com/kalekundert/signature_dispatch',
      py_modules=['signature_dispatch'],
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='~=3.6',
     )
