
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-19T10:22:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b0e6aadf2e08d5c79e3617943b8b3f6a3b7953c",
 "version": "v0.1.1-beta"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
