
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-19T02:14:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bfc42f02d3bbbc1bfa36abbc71df8a6ca863bd76",
 "version": "0.7.dev2138"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
