
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T11:49:38+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "24e9486ead8b931702829ea58c538cbbefcf21df",
 "version": "3.7.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
