
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T11:15:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8205695521fe945782eaf25cc1a52c4ff2772fcb",
 "version": "0.7.1.post.dev48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
