[tool.poetry]
name = "fastio-cli"
version = "0.1.0"
description = ""
authors = ["fastio.dev <opensource@fastio.dev>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
