
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-21T11:49:19+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6689de6fc9efac6d95a95b329c1cd48b300d5031",
 "version": "1.3.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
