[tool.poetry]
name = "mongodb-bundle"
version = "2.1.0"
description = "Mongodb support for applauncher"
authors = ["Alvaro Garcia <maxpowel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
applauncher = "^2.0.0"
pymongo = "^3.11.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
