
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T11:50:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "979ef2448462713abef8a0045697a06359f36686",
 "version": "0.7.1.post.dev54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
