
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T10:45:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab953f53d9e893131fce97059e39a50ea1b0c002",
 "version": "0.1.0a35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
