[tool.poetry]
name = "mson"
version = "0.1.0"
description = "MSON serializer/de-serializer"
authors = ["Rémy Sanchez <remy.sanchez@hyperthese.net>"]
license = "WTFPL"

[tool.poetry.dependencies]
python = "^3.8"
lark = "^0.11.3"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
isort = "^5.9.3"
ipython = "^7.27.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
