
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T10:03:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0a1809bb4f0bb7f2f12388ce8c7a703ead9133f",
 "version": "v2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
