[tool.poetry]
name="robotframework-openapidriver"
version = "1.0.0-beta.1"
description = "A library for contract-testing OpenAPI / Swagger APIs."
license = "Apache-2.0"
authors = ["Robin Mackaij"]
maintainers = ["Robin Mackaij"]
readme =  "./docs/README.md"
homepage = "https://github.com/MarketSquare/robotframework-openapidriver"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Acceptance",
    "Framework :: Robot Framework",
]
packages = [
    { include = "openapidriver", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"
robotframework = ">=4"
robotframework-pythonlibcore = ">=3"
robotframework-datadriver = ">=1.5"
requests = "*"
prance = "*"
openapi-core = "*"
openapi-spec-validator = "*"

[tool.poetry.dev-dependencies]
invoke = "*"
docutils = "*"
Pygments = "*"
robotframework-stacktrace = "*"
uvicorn = "*"
fastapi = "*"
coverage = {version = "^5.5", extras = ["toml"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
parallel = true
source = ["src"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@abstract"
]
