# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plover_plugins_manager/gui_qt/registry_explorer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistryExplorer(object):
    def setupUi(self, RegistryExplorer):
        RegistryExplorer.setObjectName("RegistryExplorer")
        RegistryExplorer.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegistryExplorer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(RegistryExplorer)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table = QtWidgets.QTableWidget(self.frame)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.table)
        self.info_frame = QtWidgets.QFrame(self.splitter)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.info_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(RegistryExplorer)
        self.table.currentItemChanged['QTableWidgetItem*','QTableWidgetItem*'].connect(RegistryExplorer.on_selection_changed)
        QtCore.QMetaObject.connectSlotsByName(RegistryExplorer)

    def retranslateUi(self, RegistryExplorer):
        _translate = QtCore.QCoreApplication.translate
        RegistryExplorer.setWindowTitle(_translate("RegistryExplorer", "Dialog"))
        self.table.setSortingEnabled(True)
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("RegistryExplorer", "Type"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("RegistryExplorer", "Name"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("RegistryExplorer", "Package"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("RegistryExplorer", "Description"))
from . import resources_rc
