
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T10:47:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac67040443f0c6efb6ea4e6fbee66dd9290f3748",
 "version": "0.8.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
