info = {"message": "Bump version 1.3.0rc4", "commit": "a22d0e969f1b6cedf1c222819daf08aef8f6e62a", "date": "2021-09-17 21:10:42 +0300", "branch": "release/1.3", "version": "1.2.0+114.ga22d0e96.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
