info = {"message": "Merge branch 'release/1.3' of github.com:heartexlabs/label-studio into release/1.3", "commit": "93dd550ffe2e5d1f45b21ab60dbcd46f068bd112", "date": "2021-09-17 19:13:01 +0300", "branch": "release/1.3", "version": "1.2.0+111.g93dd550f.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
