[tool.poetry]
name = "modpoll"
version = "0.2.15"
description = "A command line tool to communicate with modbus devices"
authors = ["Ying Shaodong <helloysd@foxmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = {version = "^1.0", python = "<3.8"}
pymodbus = "^2.5.2"
paho-mqtt = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
modpoll = "modpoll:app"
