# Generated by Django 3.1.6 on 2021-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BluelineId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(default='https://blueline.extss.de/order_log/', max_length=250, verbose_name='API Server URL')),
                ('blueline_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Blueline ID')),
                ('blueline_username', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('blueline_password', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
