[tool]
[tool.poetry]
name = "protopy-lib"
version = "0.2.0"
description = ""
authors = ["bennylut"]
packages = [{include = "protopy"}]

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
Jinja2 = "^3.0.1"
cleo = "^1.0.0a4"

[build-system]
requires = ["relaxed-poetry-core>=0.0.7"]
build-backend = "poetry.core.masonry.api"

