[tool.poetry]
name = "django-from-excel"
version = "0.1.1"
description = "Automatically builds Django models from an Excel file"
readme = 'README.md'
authors = ["John Macy <johncmacy@gmail.com>"]
repository = 'https://github.com/johncmacy/django-from-excel'
license = "MIT"
keywords = ['excel', 'convert', 'spreadsheet', 'django', 'model']

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.7"
pandas = "^1.3.3"
openpyxl = "^3.0.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
