#---- GENERAL SETTINGS

VERBOSE: False
LOGS_DIR: './logs/'
CACHE_DIR: './tmp/'

#---- DATASET URLS

URLS:
    posenet:
        split_1: 'https://zenodo.org/record/5507363/files/1.zip'
        split_2: 'https://zenodo.org/record/5507363/files/2.zip'
        split_3: 'https://zenodo.org/record/5507363/files/3.zip'
        txt_1: 'https://zenodo.org/record/5507363/files/1.txt'
        txt_2: 'https://zenodo.org/record/5507363/files/2.txt'
        txt_3: 'https://zenodo.org/record/5507363/files/3.txt'
        
    openpose:
        split_1: 'https://zenodo.org/record/5507363/files/1.zip' # to update
        split_2: 'https://zenodo.org/record/5507363/files/2.zip'
        split_3: 'https://zenodo.org/record/5507363/files/3.zip'
        txt_1: 'https://zenodo.org/record/5507363/files/1.txt'
        txt_2: 'https://zenodo.org/record/5507363/files/2.txt'
        txt_3: 'https://zenodo.org/record/5507363/files/3.txt'
   
#---- DATASET CONSTANTS
DATASET:
    T: 30
    F: 3
    
    posenet:
        K: 17
        center_1: 5
        center_2: 6
        module_keypoint: 0
        
    openpose:
        K: 17
        center_1: 5
        center_2: 6
        module_keypoint: 0  
        
#---- NORMALIZATION



#---- AUGMENTATION


