- project:
    templates:
      - ansible-role-jobs
      - build-openstack-docs-pti
      - build-release-notes-jobs-python3
      - check-requirements
      - devstack-tobiko
      - devstack-tobiko-ceph
      - devstack-tobiko-faults
      - devstack-tobiko-glance
      - devstack-tobiko-minimal
      - devstack-tobiko-octavia
      - devstack-tobiko-ovs
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-wallaby-jobs
      - publish-to-pypi
      - tobiko-infrared
    vars:
        rtd_webhook_id: '84947'
    periodic:
      jobs:
        - tobiko-infrared
        - tobiko-infrared-centos-7
        - tobiko-infrared-fedora
        - tobiko-infrared-ubuntu
        - tripleo-ci-centos-8-content-provider
        - tobiko-tripleo-functional:
            vars: &consumer_vars
              consumer_job: true
              build_container_images: false
              remove_tags:
                - build
            dependencies: &deps_cprovider
              - tripleo-ci-centos-8-content-provider
        - tobiko-tripleo-faults:
            vars: *consumer_vars
            dependencies: *deps_cprovider
