[tool.poetry]
name = "odoo-stubs"
version = "0.1-dev"
description = "Project description"
authors = ["Dmitry Voronin <dmitry665@gmail.com>"]

repository = "https://github.com/voronind/odoo-stubs"
license = "MIT"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
ipython = "*"
pytest = "*"
pytest-cov = "*"
pytest-flake8 = "*"
pytest-pythonpath = "*"
mypy = "*"
[tool.pytest]
testpaths = "tests"
norecursedirs = [".*/", "docs/"]

[tool.flake8]
max-line-length = 120
exclude = [".*/", "docs/_build/"]

[tool.coverage.run]
branch = true
source = "odoo_stubs/"

[tool.mypy]
check_untyped_defs = true

[tool.tox.tox]
envlist = "py38"
skipsdist = true

#[testenv]
#skip_install = true
#deps = pipenv
#commands =
#    pipenv install --dev --skip-lock
#    pipenv run fulltest
#
#[testenv:docs]
#basepython = python3.8
#deps =
#    pipenv
#    sphinx
#commands =
#    pipenv install --skip-lock
#    pipenv run doctest
#    pipenv run build-docs

#[scripts]
#test = "pytest --exitfirst --failed-first"
#fulltest = "pytest --flake8 --cov --cov-fail-under=80 --no-cov-on-fail odoo_stubs tests docs/conf.py"
## We use equivalent of "make mode":
## sphinx-build -M builder source build  =>
## sphinx-build -b builder -d source/doctrees source build/builder
#docs = "sphinx-autobuild --open-browser --port 0 --delay 1 -d docs/_build/doctrees docs docs/_build/html"
#doctest = "sphinx-build -b doctest -d docs/_build/doctrees docs docs/_build/doctest"
#build-docs = "sphinx-build -b html -d docs/_build/doctrees docs docs/_build/html"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
