
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T11:23:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef8dcd0d2405d4e48ba56085ad6f846628806e4b",
 "version": "0.25.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
