
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T19:13:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e819d8cab68f93f2a9d02bf0de65f2383cd7d46",
 "version": "2021.09.15post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
