[tool.poetry]
name = "multicall"
version = "0.1.3"
description = "aggregate results from multiple ethereum contract calls"
authors = ["banteg <banteeg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
eth_abi = "^2.1.0"
eth_utils = "^1.8.4"
web3 = "^5.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
