
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T09:37:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ce218c0342e45ef67f87dd079511f1d9809dde7",
 "version": "0.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
