#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pybites_tools']

package_data = \
{'': ['*'], 'pybites_tools': ['strings/*']}

install_requires = \
['requests >=2.26.0',
 'python-dotenv >=0.19.0',
 'boto3 >=1.18.36',
 'pyperclip >=1.8.2']

extras_require = \
{'test': ['pytest', 'pytest-cov', 'mypy', 'flake8', 'pre-commit']}

entry_points = \
{'console_scripts': ['email = pybites_tools.email:main',
                     's3 = pybites_tools.aws:main',
                     'zen = pybites_tools.zen:main']}

setup(name='pybites-tools',
      version='0.1',
      description='Common tools we use as PyBites',
      author=None,
      author_email='PyBites <support@pybit.es>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
