# @package _group_
_target_: classy_vision.fb.models.build_model
model_config:
  name: regnet_y_128gf
  heads:
  - name: fully_connected
    unique_id: default_head
    num_classes: 1000
    in_plane: 7392
    fork_block: trunk_output
    zero_init_bias: true
