name: hyriver-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9

  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache>=0.5.1
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - nest-asyncio
  - ujson

  # pygeoogc deps
  - defusedxml
  - owslib
  - pydantic
  - pyyaml
  - pyproj
  - requests
  - requests-cache
  - shapely
  - urllib3

  # pygeoutils deps
  - affine
  - dask
  - geopandas
  - netcdf4
  - numpy
  - rasterio
  - xarray

  # py3dep
  - click
  - scipy
  - richdem

  # pynhd deps
  - networkx
  - pandas
  - pyarrow

  # pygeohydro deps
  - folium
  - lxml
  - matplotlib-base

  # optional deps to speed up xarray and geopandas
  - bottleneck
  - pygeos

  # plotting deps
  - contextily
  - mapclassify
  - cartopy
  - colorcet

  # dev deps
  - codespell
  - nox
  - pre-commit
  - psutil
  - pytest
  - pytest-clarity
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - setuptools-scm

  # ward deps
  - tomli
  - markupsafe
  - click-completion
  - click-default-group
  - colorama
  - commonmark
  - cucumber-tag-expressions
  - jinja2
  - pprintpp
  - pygments
  - rich
  - shellingham

  - pip
  - pip:
    - ward

    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/pynhd.git
    - git+https://github.com/cheginit/py3dep.git
    - git+https://github.com/cheginit/pydaymet.git
    - git+https://github.com/cheginit/pygeohydro.git
