
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T20:35:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a363d70073f21bce757fbe20a1b7a393cf8b4b9",
 "version": "1.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
