
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-25T15:41:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c96cc6f6a2187956645259bb5f4c0468306e1722",
 "version": "0.8.13b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
