[tool.poetry]
name = "fastapi-project"
version = "0.1.0"
description = "Create FastAPI Application using this CLI"
authors = ["Gian Carlo Llanes Garcia"]
readme = "README.md"

[tool.poetry.scripts]
fastapi-cli = "fastapi_project.manage:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"