[tool.poetry]
name = "scilib"
version = "0.0.14"
description = "scilib"
license = "MIT"
readme = "README.md"
authors = ["phyng <phyngk@gmail.com>"]
homepage = "https://github.com/phyng/scilib"
repository = "https://github.com/phyng/scilib"
classifiers = [
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.scripts]
scilib-wos-import = "scilib.scripts.wos_import:run"
scilib-cnki-import = "scilib.scripts.cnki_import:run"
scilib-db-trans = "scilib.scripts.db_trans:run"
scilib-gender-benchmark = "scilib.gender.benchmark.benchmark:run"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"
jupyter = "^1.0.0"
numpy = "^1.18.2"
xlrd = "^1.2.0"
matplotlib = "^3.2.1"
scipy = "^1.4.1"
requests = "^2.23.0"
openpyxl = "^3.0.3"
orjson = "^3.2.1"
nltk = "^3.5"
pypinyin = "^0.38.1"
gender-guesser = "0.4.0"
tabulate = "^0.8.9"
agefromname = "^0.0.8"
genderizer = "^0.1.2"
naiveBayesClassifier = "^0.1.3"
pyquery = "^1.4.3"
libs = "^0.0.10"
jupyterlab = "^3.0.16"
nameparser = "^1.0.6"
Unidecode = "^1.2.0"
aiohttp = "^3.7.4"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
sphinx = "^2.4.4"
twine = "^3.1.1"
coverage = "^5.0.3"
flake8 = "^3.7.9"
sphinx_rtd_theme = "^0.4.3"
wheel = "^0.34.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
