
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-16T17:42:57-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "72ee784be3b91fb31feabe4cd218a09f1f63140b",
 "version": "2021.9.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
