
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T15:50:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e3104a7242f5bcba4d3a64483c4903e0c6dce5c",
 "version": "0.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
