
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T10:25:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e68baaa51a4d717650dc20823a2767b4fbd7aacf",
 "version": "2021.09.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
