# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_crawler_data_processor/crawler_data_processor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from th2_grpc_common import common_pb2 as th2__grpc__common_dot_common__pb2
from th2_grpc_data_provider import data_provider_template_pb2 as th2__grpc__data__provider_dot_data__provider__template__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='th2_grpc_crawler_data_processor/crawler_data_processor.proto',
  package='th2.crawler.dataprocessor',
  syntax='proto3',
  serialized_options=b'\n+com.exactpro.th2.crawler.dataprocessor.grpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n<th2_grpc_crawler_data_processor/crawler_data_processor.proto\x12\x19th2.crawler.dataprocessor\x1a\x1cth2_grpc_common/common.proto\x1a\x33th2_grpc_data_provider/data_provider_template.proto\"?\n\x0b\x43rawlerInfo\x12\x30\n\x02id\x18\x01 \x01(\x0b\x32$.th2.crawler.dataprocessor.CrawlerId\"\x19\n\tCrawlerId\x12\x0c\n\x04name\x18\x01 \x01(\t\"x\n\x11\x44\x61taProcessorInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1c\n\x08\x65vent_id\x18\x03 \x01(\x0b\x32\x08.EventIDH\x00\x12 \n\nmessage_id\x18\x04 \x01(\x0b\x32\n.MessageIDH\x00\x42\x04\n\x02id\"d\n\x10\x45ventDataRequest\x12\x30\n\x02id\x18\x01 \x01(\x0b\x32$.th2.crawler.dataprocessor.CrawlerId\x12\x1e\n\nevent_data\x18\x02 \x03(\x0b\x32\n.EventData\"j\n\x12MessageDataRequest\x12\x30\n\x02id\x18\x01 \x01(\x0b\x32$.th2.crawler.dataprocessor.CrawlerId\x12\"\n\x0cmessage_data\x18\x02 \x03(\x0b\x32\x0c.MessageData\"X\n\rEventResponse\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x08.EventID\x12\x31\n\x06status\x18\x02 \x01(\x0b\x32!.th2.crawler.dataprocessor.Status\"]\n\x0fMessageResponse\x12\x17\n\x03ids\x18\x01 \x03(\x0b\x32\n.MessageID\x12\x31\n\x06status\x18\x02 \x01(\x0b\x32!.th2.crawler.dataprocessor.Status\"$\n\x06Status\x12\x1a\n\x12handshake_required\x18\x01 \x01(\x08\x32\xcb\x02\n\rDataProcessor\x12h\n\x0e\x63rawlerConnect\x12&.th2.crawler.dataprocessor.CrawlerInfo\x1a,.th2.crawler.dataprocessor.DataProcessorInfo\"\x00\x12\x64\n\tsendEvent\x12+.th2.crawler.dataprocessor.EventDataRequest\x1a(.th2.crawler.dataprocessor.EventResponse\"\x00\x12j\n\x0bsendMessage\x12-.th2.crawler.dataprocessor.MessageDataRequest\x1a*.th2.crawler.dataprocessor.MessageResponse\"\x00\x42/\n+com.exactpro.th2.crawler.dataprocessor.grpcP\x01\x62\x06proto3'
  ,
  dependencies=[th2__grpc__common_dot_common__pb2.DESCRIPTOR,th2__grpc__data__provider_dot_data__provider__template__pb2.DESCRIPTOR,])




_CRAWLERINFO = _descriptor.Descriptor(
  name='CrawlerInfo',
  full_name='th2.crawler.dataprocessor.CrawlerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='th2.crawler.dataprocessor.CrawlerInfo.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=237,
)


_CRAWLERID = _descriptor.Descriptor(
  name='CrawlerId',
  full_name='th2.crawler.dataprocessor.CrawlerId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='th2.crawler.dataprocessor.CrawlerId.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=264,
)


_DATAPROCESSORINFO = _descriptor.Descriptor(
  name='DataProcessorInfo',
  full_name='th2.crawler.dataprocessor.DataProcessorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='th2.crawler.dataprocessor.DataProcessorInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='th2.crawler.dataprocessor.DataProcessorInfo.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='th2.crawler.dataprocessor.DataProcessorInfo.event_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='th2.crawler.dataprocessor.DataProcessorInfo.message_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='id', full_name='th2.crawler.dataprocessor.DataProcessorInfo.id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=266,
  serialized_end=386,
)


_EVENTDATAREQUEST = _descriptor.Descriptor(
  name='EventDataRequest',
  full_name='th2.crawler.dataprocessor.EventDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='th2.crawler.dataprocessor.EventDataRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_data', full_name='th2.crawler.dataprocessor.EventDataRequest.event_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=488,
)


_MESSAGEDATAREQUEST = _descriptor.Descriptor(
  name='MessageDataRequest',
  full_name='th2.crawler.dataprocessor.MessageDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='th2.crawler.dataprocessor.MessageDataRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_data', full_name='th2.crawler.dataprocessor.MessageDataRequest.message_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=596,
)


_EVENTRESPONSE = _descriptor.Descriptor(
  name='EventResponse',
  full_name='th2.crawler.dataprocessor.EventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='th2.crawler.dataprocessor.EventResponse.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='th2.crawler.dataprocessor.EventResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=686,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='th2.crawler.dataprocessor.MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='th2.crawler.dataprocessor.MessageResponse.ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='th2.crawler.dataprocessor.MessageResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=781,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='th2.crawler.dataprocessor.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='handshake_required', full_name='th2.crawler.dataprocessor.Status.handshake_required', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=783,
  serialized_end=819,
)

_CRAWLERINFO.fields_by_name['id'].message_type = _CRAWLERID
_DATAPROCESSORINFO.fields_by_name['event_id'].message_type = th2__grpc__common_dot_common__pb2._EVENTID
_DATAPROCESSORINFO.fields_by_name['message_id'].message_type = th2__grpc__common_dot_common__pb2._MESSAGEID
_DATAPROCESSORINFO.oneofs_by_name['id'].fields.append(
  _DATAPROCESSORINFO.fields_by_name['event_id'])
_DATAPROCESSORINFO.fields_by_name['event_id'].containing_oneof = _DATAPROCESSORINFO.oneofs_by_name['id']
_DATAPROCESSORINFO.oneofs_by_name['id'].fields.append(
  _DATAPROCESSORINFO.fields_by_name['message_id'])
_DATAPROCESSORINFO.fields_by_name['message_id'].containing_oneof = _DATAPROCESSORINFO.oneofs_by_name['id']
_EVENTDATAREQUEST.fields_by_name['id'].message_type = _CRAWLERID
_EVENTDATAREQUEST.fields_by_name['event_data'].message_type = th2__grpc__data__provider_dot_data__provider__template__pb2._EVENTDATA
_MESSAGEDATAREQUEST.fields_by_name['id'].message_type = _CRAWLERID
_MESSAGEDATAREQUEST.fields_by_name['message_data'].message_type = th2__grpc__data__provider_dot_data__provider__template__pb2._MESSAGEDATA
_EVENTRESPONSE.fields_by_name['id'].message_type = th2__grpc__common_dot_common__pb2._EVENTID
_EVENTRESPONSE.fields_by_name['status'].message_type = _STATUS
_MESSAGERESPONSE.fields_by_name['ids'].message_type = th2__grpc__common_dot_common__pb2._MESSAGEID
_MESSAGERESPONSE.fields_by_name['status'].message_type = _STATUS
DESCRIPTOR.message_types_by_name['CrawlerInfo'] = _CRAWLERINFO
DESCRIPTOR.message_types_by_name['CrawlerId'] = _CRAWLERID
DESCRIPTOR.message_types_by_name['DataProcessorInfo'] = _DATAPROCESSORINFO
DESCRIPTOR.message_types_by_name['EventDataRequest'] = _EVENTDATAREQUEST
DESCRIPTOR.message_types_by_name['MessageDataRequest'] = _MESSAGEDATAREQUEST
DESCRIPTOR.message_types_by_name['EventResponse'] = _EVENTRESPONSE
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrawlerInfo = _reflection.GeneratedProtocolMessageType('CrawlerInfo', (_message.Message,), {
  'DESCRIPTOR' : _CRAWLERINFO,
  '__module__' : 'th2_grpc_crawler_data_processor.crawler_data_processor_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.dataprocessor.CrawlerInfo)
  })
_sym_db.RegisterMessage(CrawlerInfo)

CrawlerId = _reflection.GeneratedProtocolMessageType('CrawlerId', (_message.Message,), {
  'DESCRIPTOR' : _CRAWLERID,
  '__module__' : 'th2_grpc_crawler_data_processor.crawler_data_processor_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.dataprocessor.CrawlerId)
  })
_sym_db.RegisterMessage(CrawlerId)

DataProcessorInfo = _reflection.GeneratedProtocolMessageType('DataProcessorInfo', (_message.Message,), {
  'DESCRIPTOR' : _DATAPROCESSORINFO,
  '__module__' : 'th2_grpc_crawler_data_processor.crawler_data_processor_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.dataprocessor.DataProcessorInfo)
  })
_sym_db.RegisterMessage(DataProcessorInfo)

EventDataRequest = _reflection.GeneratedProtocolMessageType('EventDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVENTDATAREQUEST,
  '__module__' : 'th2_grpc_crawler_data_processor.crawler_data_processor_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.dataprocessor.EventDataRequest)
  })
_sym_db.RegisterMessage(EventDataRequest)

MessageDataRequest = _reflection.GeneratedProtocolMessageType('MessageDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEDATAREQUEST,
  '__module__' : 'th2_grpc_crawler_data_processor.crawler_data_processor_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.dataprocessor.MessageDataRequest)
  })
_sym_db.RegisterMessage(MessageDataRequest)

EventResponse = _reflection.GeneratedProtocolMessageType('EventResponse', (_message.Message,), {
  'DESCRIPTOR' : _EVENTRESPONSE,
  '__module__' : 'th2_grpc_crawler_data_processor.crawler_data_processor_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.dataprocessor.EventResponse)
  })
_sym_db.RegisterMessage(EventResponse)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'th2_grpc_crawler_data_processor.crawler_data_processor_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.dataprocessor.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'th2_grpc_crawler_data_processor.crawler_data_processor_pb2'
  # @@protoc_insertion_point(class_scope:th2.crawler.dataprocessor.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None

_DATAPROCESSOR = _descriptor.ServiceDescriptor(
  name='DataProcessor',
  full_name='th2.crawler.dataprocessor.DataProcessor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=822,
  serialized_end=1153,
  methods=[
  _descriptor.MethodDescriptor(
    name='crawlerConnect',
    full_name='th2.crawler.dataprocessor.DataProcessor.crawlerConnect',
    index=0,
    containing_service=None,
    input_type=_CRAWLERINFO,
    output_type=_DATAPROCESSORINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendEvent',
    full_name='th2.crawler.dataprocessor.DataProcessor.sendEvent',
    index=1,
    containing_service=None,
    input_type=_EVENTDATAREQUEST,
    output_type=_EVENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='th2.crawler.dataprocessor.DataProcessor.sendMessage',
    index=2,
    containing_service=None,
    input_type=_MESSAGEDATAREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAPROCESSOR)

DESCRIPTOR.services_by_name['DataProcessor'] = _DATAPROCESSOR

# @@protoc_insertion_point(module_scope)
