# @package _group_
_target_: pytorch.recipes.graph.torchgraph.module.models.gcn.GCN
node_input_dim: 500
node_projection_dim: 30
edge_input_dim: 0
output_dim: 2
hidden_dim: 256
num_gnn_layers: 2
bias: true
