# Generated by Django 3.0.6 on 2020-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sarscov2", "0005_auto_20200527_1448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coronaviruskap",
            name="protocol",
            field=models.CharField(default="meta_edc", max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalcoronaviruskap",
            name="protocol",
            field=models.CharField(default="meta_edc", max_length=50),
        ),
    ]
