# Generated by Django 3.2.4 on 2021-07-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sarscov2", "0006_auto_20200527_2155"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coronaviruskap",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Coronavirus KAP",
                "verbose_name_plural": "Coronavirus KAP",
            },
        ),
    ]
