
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T18:31:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c83db16bab326f46145d6bb797c48670cd144f98",
 "version": "2021.09.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
