
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T08:56:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba9ce2e012a07686e19454acc58ccb0cbe249585",
 "version": "0.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
