# @package _group_
_target_: pytext.contrib.pytext_lib.models.ByteDocModel
embedding_dim: 256
kernel_num: 128
kernel_sizes:
  - 7
  - 7
  - 7
dropout: 0.3
dense_dim: 0
decoder_hidden_dims:
  - 64
  - 32
out_dim: 2
