[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "flake8_formatter_vscode"
authors = [{ name = "Rodolphe Pelloux-Prayer", email = "rodolphe@damsy.net" }]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
keywords = ["flake8", "formatter", "vscode"]
requires-python = ">=3.6"
dependencies = ["flake8"]

[project.urls]
Source = "https://gitlab.com/RoPP/flake8-formatter-vscode"

[project.optional-dependencies]
dev = ["black", "mypy", "flake8"]
test = ["pytest", "pytest-sugar"]

[project.entry-points."flake8.report"]
vscode = "flake8_formatter_vscode:VscodePathFormatter"

[tool.mypy]
strict = true
