#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['flake8_formatter_vscode']

package_data = \
{'': ['*']}

install_requires = \
['flake8']

extras_require = \
{'dev': ['black', 'mypy', 'flake8'], 'test': ['pytest', 'pytest-sugar']}

entry_points = \
{'flake8.report': ['vscode = flake8_formatter_vscode:VscodePathFormatter']}

setup(name='flake8_formatter_vscode',
      version='0.0.1',
      description='Flake8 formatter.',
      author=None,
      author_email='Rodolphe Pelloux-Prayer <rodolphe@damsy.net>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
