"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import th2_grpc_common.common_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class MatchingField(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PATH_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int

    @property
    def path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    value: typing.Text = ...

    def __init__(self,
        *,
        path : typing.Optional[typing.Iterable[typing.Text]] = ...,
        value : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"path",b"path",u"value",b"value"]) -> None: ...
global___MatchingField = MatchingField

class ResponseMapper(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    MATCHING_FIELDS_FIELD_NUMBER: builtins.int
    IS_PASSED_FIELD_NUMBER: builtins.int
    message_type: typing.Text = ...
    is_passed: builtins.bool = ...

    @property
    def matching_fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MatchingField]: ...

    def __init__(self,
        *,
        message_type : typing.Text = ...,
        matching_fields : typing.Optional[typing.Iterable[global___MatchingField]] = ...,
        is_passed : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"is_passed",b"is_passed",u"matching_fields",b"matching_fields",u"message_type",b"message_type"]) -> None: ...
global___ResponseMapper = ResponseMapper

class MessageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TIMEOUT_FIELD_NUMBER: builtins.int
    RESPONSE_MAPPERS_FIELD_NUMBER: builtins.int
    STREAM_FIELD_NUMBER: builtins.int
    PARENT_EVENT_ID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    timeout: builtins.int = ...
    description: typing.Text = ...

    @property
    def response_mappers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResponseMapper]: ...

    @property
    def stream(self) -> th2_grpc_common.common_pb2.ConnectionID: ...

    @property
    def parent_event_id(self) -> th2_grpc_common.common_pb2.EventID: ...

    def __init__(self,
        *,
        timeout : builtins.int = ...,
        response_mappers : typing.Optional[typing.Iterable[global___ResponseMapper]] = ...,
        stream : typing.Optional[th2_grpc_common.common_pb2.ConnectionID] = ...,
        parent_event_id : typing.Optional[th2_grpc_common.common_pb2.EventID] = ...,
        description : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"parent_event_id",b"parent_event_id",u"stream",b"stream"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"description",b"description",u"parent_event_id",b"parent_event_id",u"response_mappers",b"response_mappers",u"stream",b"stream",u"timeout",b"timeout"]) -> None: ...
global___MessageRequest = MessageRequest

class MessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESPONSE_MESSAGE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def response_message(self) -> th2_grpc_common.common_pb2.Message: ...

    @property
    def status(self) -> th2_grpc_common.common_pb2.RequestStatus: ...

    def __init__(self,
        *,
        response_message : typing.Optional[th2_grpc_common.common_pb2.Message] = ...,
        status : typing.Optional[th2_grpc_common.common_pb2.RequestStatus] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"response_message",b"response_message",u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"response_message",b"response_message",u"status",b"status"]) -> None: ...
global___MessageResponse = MessageResponse

class SendMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    CHECKPOINT_ID_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> th2_grpc_common.common_pb2.RequestStatus: ...

    @property
    def checkpoint_id(self) -> th2_grpc_common.common_pb2.Checkpoint: ...

    def __init__(self,
        *,
        status : typing.Optional[th2_grpc_common.common_pb2.RequestStatus] = ...,
        checkpoint_id : typing.Optional[th2_grpc_common.common_pb2.Checkpoint] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"checkpoint_id",b"checkpoint_id",u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"checkpoint_id",b"checkpoint_id",u"status",b"status"]) -> None: ...
global___SendMessageResponse = SendMessageResponse

class PlaceMessageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_FIELD_NUMBER: builtins.int
    PARENT_EVENT_ID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    description: typing.Text = ...

    @property
    def message(self) -> th2_grpc_common.common_pb2.Message: ...

    @property
    def parent_event_id(self) -> th2_grpc_common.common_pb2.EventID: ...

    def __init__(self,
        *,
        message : typing.Optional[th2_grpc_common.common_pb2.Message] = ...,
        parent_event_id : typing.Optional[th2_grpc_common.common_pb2.EventID] = ...,
        description : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"message",b"message",u"parent_event_id",b"parent_event_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"description",b"description",u"message",b"message",u"parent_event_id",b"parent_event_id"]) -> None: ...
global___PlaceMessageRequest = PlaceMessageRequest

class PlaceMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESPONSE_MESSAGE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CHECKPOINT_ID_FIELD_NUMBER: builtins.int

    @property
    def response_message(self) -> th2_grpc_common.common_pb2.Message: ...

    @property
    def status(self) -> th2_grpc_common.common_pb2.RequestStatus: ...

    @property
    def checkpoint_id(self) -> th2_grpc_common.common_pb2.Checkpoint: ...

    def __init__(self,
        *,
        response_message : typing.Optional[th2_grpc_common.common_pb2.Message] = ...,
        status : typing.Optional[th2_grpc_common.common_pb2.RequestStatus] = ...,
        checkpoint_id : typing.Optional[th2_grpc_common.common_pb2.Checkpoint] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"checkpoint_id",b"checkpoint_id",u"response_message",b"response_message",u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"checkpoint_id",b"checkpoint_id",u"response_message",b"response_message",u"status",b"status"]) -> None: ...
global___PlaceMessageResponse = PlaceMessageResponse
