
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-16T20:53:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "df5013bd291e2a99b27e1a014d8a012ea2072122",
 "version": "0.0.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
