{% set name = "py_dateinfer" %}
{% set version = "0.4.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "0a4df1c80be414a1b7237d7e85b0b11cb315bfa432107dd7bc28765eb4674ea9"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - pytz
    - wheel
  run:
    - python
    - pytz
    - wheel

test:
  imports:
    - hidateinfer
  requires:
    - pytest >=3

about:
  home: "https://github.com/jeffreystarr/dateinfer"
  license: "Apache Software"
  license_family: "APACHE"
  license_file: ""
  summary: "Infers date format from examples, by using a series of pattern matching and rewriting rules to compute a 'best guess' datetime.strptime format string give a list of example date strings."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
