
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T10:16:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "708cdc2f123d122b7646efa7da19085f0c642e33",
 "version": "0.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
