[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "logitech_presenter"
authors = [{name = "Adam Allevato", email = "adam.d.allevato@gmail.com"}]
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = ["pynput"]

[project.urls]
Home = "https://github.com/Kukanani/logitech-presenter"
