#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['logitech_presenter']

package_data = \
{'': ['*']}

setup(name='logitech_presenter',
      version='1.0.1',
      description='Listens to the Logitech Presenter and fires callbacks appropriately.',
      author=None,
      author_email='Adam Allevato <adam.d.allevato@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
