
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T11:24:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1752c3bef53ab854846d4d8d2ac1dcf9a8e8bcb1",
 "version": "v0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
