[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "savings"
authors = [{name = "OV", email = "olav.vahtras@gmail.com"}]
dynamic = ["version", "description"]
