[tool.poetry]
name = "andyao.mdspliter.tree"
version = "0.1.0"
description = "Tree data structure for mdsplitter."
authors = ["zen96285 <zen96285@gmail.com>"]
packages = [
    { include = "andyao" }
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
