
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-16T07:07:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d50310f09995d4d75be040175c05ec270b5da2ea",
 "version": "4.5.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
