[tool.poetry]
name = "kslurm"
version = "0.2.2"
description = "Helper scripts and wrappers for running commands on SLURM compute clusters."
license = "MIT"
readme = "README.md"
authors = ["Peter Van Dyken <pvandyk2@uwo.ca>"]
repository = "https://github.com/pvandyken/kslurm"
keywords = ["slurm", "compute cluster"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Utilities",
    "Typing :: Typed"
]
packages = [
    { include = "kslurm" }
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
attrs = "^21.2.0"
colorama = "^0.4.4"
typing-extensions = "^3.10"
rich = "^10.9.0"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
pytest = "^6.2.5"
tox = "^3.24.3"
coverage = "^5.5"
tox-poetry-installer = {extras = ["poetry"], version = "^0.8.1"}
hypothesis = "^6.20.0"

[tool.poetry.scripts]
kbatch = 'kslurm.submission.kbatch:main'
krun = 'kslurm.submission.krun:main'
kjupyter = 'kslurm.submission.kjupyter:main'
kslurm = 'kslurm.kslurm:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37, py38, py39
isolated_build = True

[testenv]
deps =
    pytest
    tabulate
    hypothesis
    rich
install_project_deps = true
commands =
    pytest
"""
