
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T20:20:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f6c59b7451cd1bfe7297a391f2014f1efc2f084",
 "version": "v2.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
