
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-20T09:58:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9068ca18c7377e5731a8b0513770f5f580f4bf7",
 "version": "2.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
