
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-16T09:10:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b02b1b11ffb29fc2a3cb6e2c1c7344d8007ee936",
 "version": "v1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
