
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T20:15:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e91a3a1a9f3b6e3bb10eb72c6cfbd51fbdbf4e43",
 "version": "1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
