
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T18:49:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d452919bfc60d95e059c8c169646f0fddf29e81b",
 "version": "0.3.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
