[tool.poetry]
name = "kungfuai-env"
version = "0.1.0"
description = "Environment handling to simplify development environments"
authors = ["Endurance Idehen <jeidehen@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
test    = "./scripts/test"
publish = "./scripts/publish"