repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
      - id: trailing-whitespace
        files: \.py$
      - id: end-of-file-fixer
        files: \.py$
      - id: check-yaml
        files: \.yaml$
      - id: check-added-large-files
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
    - id: flake8
      args: [ '--ignore','D200,D400','--max-line-length','80' ]
      additional_dependencies: [
            'flake8-bugbear',
            'flake8-docstrings>=1.3.1',
            'flake8-typing-imports>=1.1'
        ]
      files: \.py$

default_language_version:
  python: python3.8
