
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-03T23:49:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1876db23b1a93550b40ba07e579c222f49c8c109",
 "version": "1.0.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
