#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='spinny',
      version='1.1.0',
      description='A simple spinner library.',
      author='Pradhyum R',
      author_email='drpradhyum2016@outlook.com',
      url='https://github.com/techieji/spin',
      py_modules=['spinny'],
     )
