
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T16:02:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dba3598324b1daeee6eb431dd698567b17fe6a2c",
 "version": "0.4.71"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
