[project]
name = "cotton2k"
version = "5.0.0a8"
description = "Reimplementation for Cotton2k simulation model"
authors = [{ name = "Tang Ziya", email = "tcztzy@gmail.com" }]
readme = "README.rst"
keywords = ["cotton", "simulation", "model"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Hydrology",
]
dependencies = [
    "cotton2k.core>=0.1a1",
]

[project.urls]
homepage = "https://github.com/tcztzy/cotton2k"
repository = "https://github.com/tcztzy/cotton2k"

[build-system]
requires = ["pyproject-toml == 0.0.10"]
build-backend = "pyproject_toml.build_system.build_backend"
