[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "456789999999test"
version = "1.0.0"
description = "Jupyter Notebook Image Classification assessment tool"
license = "BSD-3-Clause"
authors = [
    "test <test@gmail.com>"
]
readme = 'README.md'
repository = "https://github.com/22342432/test"
homepage = "https://github.com/3421321321/test"

[tool.poetry.dependencies]
python = "~2.7 || ^3.2"
fpdf = "*"
PyPDF2 = "*"