# See: https://pre-commit.com/

repos:
-   repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    - id: reorder-python-imports
