
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T09:18:17-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4c88a0402dec61d466edb1fa5dbda4544f7a738",
 "version": "v1.2.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
