#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='number_names',
      version='0.0.3',
      description='This module provides functions for getting the English names of numbers.',
      author='Tom Fryers',
      author_email=None,
      url=None,
      py_modules=['number_names'],
      python_requires='>=3.9',
     )
