# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"__numpy_time_series": "00_SimulateData.ipynb",
         "pandas_time_series": "00_SimulateData.ipynb",
         "simple": "01_Moving_Average.ipynb",
         "weighted": "01_Moving_Average.ipynb",
         "SMA": "01_Moving_Average.ipynb",
         "WMA": "01_Moving_Average.ipynb",
         "__single": "02_Smoothing.ipynb",
         "__double": "02_Smoothing.ipynb",
         "holt_winters": "02_Smoothing.ipynb",
         "SINGLE": "02_Smoothing.ipynb",
         "DOUBLE": "02_Smoothing.ipynb"}

modules = ["simulate_data.py",
           "moving_average.py",
           "smoothing.py"]

doc_url = "https://kikejimenez.github.io/time_series_model_basics/"

git_url = "https://github.com/kikejimenez/time_series_model_basics/tree/master/"

def custom_doc_links(name): return None
