
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T18:35:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "10e85998f0933d917cbe0d91a97ed9bbf7fbdcba",
 "version": "1.5.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
