
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T11:13:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "18749d4b199a467bba729a960d3f67f7e401cc93",
 "version": "0.8.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
