version: "3.9"
volumes:
  pg_data:
services:
  postgres:
    image: library/postgres:13
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: wilddog
      POSTGRES_PASSWORD: wilddog
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: library/adminer:4.7
    depends_on:
      - postgres
    ports:
      - "60806:8080"
    environment:
      ADMINER_DESIGN: brade
  wilddog:
    image: docker.nimworks.com/wilddog:chore_add-run-script-image
    depends_on:
      - postgres
    ports:
      - "50705:50705"
    volumes:
      - ./wilddog.toml:/opt/wilddog/wilddog.toml
