
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T08:40:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7666bb6f32f6998f7835cec3868d981e4c2a8dc",
 "version": "21.10.00a+40.gb7666bb"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
