[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "qpsolvers"
author = "Stéphane Caron"
author-email = "stephane.caron@normalesup.org"
home-page = "https://github.com/stephane-caron/qpsolvers"
description-file = "README.md"
requires-python = ">=3.6"
requires = ["quadprog >=0.1.8"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering :: Mathematics",
]

[tool.flit.metadata.requires-extra]
doc = ["sphinx"]

[tool.flit.metadata.urls]
Documentation = "https://scaron.info/doc/qpsolvers/"
