
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T16:32:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "66180430ee0985e0d3e73e2bab434db4df801b60",
 "version": "5.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
