[tool.poetry]
name = "suade-reverse-repo"
version = "0.1.4"
description = "This package includes classes to model reverse repo transactions and calculate the associated ktcd factor."
authors = ["Moe Bourji <mrbourji@gmail.com>"]


[tool.poetry.dependencies]
python = "3.8"
pydantic = "^1.8.2"
pandas = "^1.3.3"
atomicwrites = "1.4.0"
attrs = "21.2.0"
colorama = "0.4.4"
iniconfig = "1.1.1"
numpy = "1.21.2"
packaging = "21.0"
pluggy = "1.0.0"
py = "1.10.0"
pyparsing = "2.4.7"
pytz = "2021.1"
six = "1.16.0"
toml = "0.10.2"
typing-extensions = "^3.10.0"
pytest = "^6.2.5"


[tool.poetry.dev-dependencies]
pytest = "6.2.5"




[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
