
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T17:22:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6f5b35a09416ce85bbc045be112d7b8c9ac8571",
 "version": "0.15.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
