# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"random_time_series": "01_Smoothing.ipynb",
         "simple": "00_Moving_Average.ipynb",
         "weighted": "00_Moving_Average.ipynb",
         "SMA": "00_Moving_Average.ipynb",
         "WMA": "00_Moving_Average.ipynb",
         "__simple": "01_Smoothing.ipynb",
         "__double": "01_Smoothing.ipynb",
         "holt_winters": "01_Smoothing.ipynb",
         "SIMPLE": "01_Smoothing.ipynb",
         "DOUBLE": "01_Smoothing.ipynb"}

modules = ["moving_average.py",
           "smoothing.py"]

doc_url = "https://kikejimenez.github.io/time_series_model_basics/"

git_url = "https://github.com/kikejimenez/time_series_model_basics/tree/{branch}/"

def custom_doc_links(name): return None
