
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T13:55:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8c3fdb0907bbad267133366c5a2e0dbe974c996",
 "version": "1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
