
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T18:10:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a955ca1a66f9019cc940447c3e0fabb32e594a7",
 "version": "21.10.00a+47.g1a955ca"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
