
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T19:24:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eafecf11b0a78d4136ad8097b89c5bb16ae9da19",
 "version": "v2.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
