[tool.poetry]
name = "modpoll"
version = "0.2.22"
description = "A command line tool to communicate with modbus devices"
authors = ["Ying Shaodong <helloysd@foxmail.com>"]
readme = "README.md"
homepage = "https://helloysd.gitlab.io/modpoll"
repository = "https://gitlab.com/helloysd/modpoll"
license = "MIT"
include = [
  "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = {version = "^1.0", python = "<3.8"}
pymodbus = "^2.5.2"
paho-mqtt = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
sphinx = "^4.2.0"
sphinx-argparse = "^0.3.1"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
modpoll = "modpoll:app"
