defaults:
  - default
  - tokenizer_trainer: base_tokenizer_trainer
  - tokenizer_trainer/tokenizer: base_tokenizer
  - tokenizer: base_pretrained_tokenizer
  - dataset: base_dataset
  - data: base_data
  - model: base_model
  - optimizer: base_optimizer
  - optimizer/scheduler: base_scheduler
  - trainer: base_trainer
  - logger: base_logger
