
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-18T16:19:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "99fbef6ef195545c283d1a8164d1f2604b9b650f",
 "version": "2.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
