
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T11:44:34+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "242f8ef66911d79257b080c962d89624164d5f74",
 "version": "3.7.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
