
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T17:02:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5af1a9f5c8e0bdf6bed8c2785dac6ca69d3297a0",
 "version": "0.0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
