
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T17:38:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7486a68a5c8722c1b079e0a76395ff341b553037",
 "version": "2021.09.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
