
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T11:24:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "afae8e7d91b81f33a09c54b0427ac5305aa37b0b",
 "version": "0.7.1.post.dev50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
