
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T10:57:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "61eb869fb1e5524e74aab03d6ced6556a95faa49",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
