
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T12:25:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fdb5d381c7471f5aba32b644ef6863e85b2581b",
 "version": "0.7.1.post.dev56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
