
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-19T16:42:06+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ecf003c771e9db7626d3d85bbfd34199cd8d09e",
 "version": "1.3.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
