
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T18:57:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "abe6f565f37670101a7a2191c17df18610f3de3e",
 "version": "v11.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
