[tool.poetry]
name = "grumpy_checks"
version = "0.1.7"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.7"
rich = "^10.9.0"
toml = "^0.10.2"
cleo = "^0.8.1"
flake8 = "^3.9.2"
pydocstyle = "^6.1.1"

[tool.poetry.scripts]
grumpy = "grumpy_checks.application:main"
test = "scripts:test"
codecov = "scripts:coverage_report"
document = "scripts:documentation"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
autopep8 = "^1.5.7"
pyfakefs = "^4.5.1"
coverage = "^5.5"
pydoctor = "^21.2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
