
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T20:28:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "61ee2dfc0c0147336c2bd33328ef5467736896b9",
 "version": "0.8.340"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
