[tool.poetry]
name = "fledge"
version = "0.1.0-alpha.3"
description = "Fledge"
authors = ["Benjamin D. Killeen <killeen@jhu.edu>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/benjamindkilleen/fledge"
repository = "https://github.com/benjamindkilleen/fledge"
documentation = "https://fledge.readthedocs.io"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    # "Programming Language :: Python :: 3.6",
    # "Programming Language :: Python :: 3.7",
    # "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.urls]
Changelog = "https://github.com/benjamindkilleen/fledge/releases"

[tool.poetry.dependencies]
python = ">=3.9,<4"
click = "^8.0.1"
numpy = "^1.21.1"
networkx = "^2.6.1"
pyvis = "^0.1.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
coverage = {extras = ["toml"], version = "^5.4"}
safety = "^1.10.3"
mypy = "^0.910"
typeguard = "^2.12.1"
xdoctest = {extras = ["colors"], version = "^0.15.8"}
sphinx = "^4.1.1"
sphinx-autobuild = "^2021.3.14"
pre-commit = "^2.15.0"
flake8 = "^3.9.2"
black = "^21.9b0"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.1"
darglint = "^1.8.0"
reorder-python-imports = "^2.5.0"
pre-commit-hooks = "^4.0.1"
sphinx-click = "^3.0.1"
Pygments = "^2.9.0"
pydata-sphinx-theme = "^0.6.3"

[tool.poetry.scripts]
fledge = "fledge.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["fledge"]

[tool.coverage.report]
show_missing = true
fail_under = 0                  # TODO: set higher.

[tool.mypy]
strict = false # TODO: make true.
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
