
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T11:10:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f91e4726cfc71d67e225d081f1a7134741c515c1",
 "version": "0.7.1.post.dev58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
