
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T10:46:04+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "26b1a2438bd682a1d594544e92221bba8523fe7c",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
