info = {"message": "Exclude selected items from Label Stream when nothing's selected (#1476)", "commit": "1589078bef8dc74170202c78d1e0b15aa1c3dea0", "date": "2021-09-17 20:55:28 +0300", "branch": "release/1.3", "version": "1.2.0+113.g1589078b.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
