
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T09:48:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "034a336b92ef0a66b3529a46def3cd369280fd07",
 "version": "1.21.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
