
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-13T21:52:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c9642c0bfc16c722e5c9b9873633d9ef0b7cc76",
 "version": "4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
