
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-23T20:55:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6f8b1cbb223ffe31ebd91c28f868b3628c85f07",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
