[tool.poetry]
name = "palette-sdk"
version = "0.0.2"
description = ""
authors = ["Stargazer 838 <stargazers838@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"
cryptography = "^3.4.8"
terra_sdk = "^1.0.0-b2"
python-dotenv = "^0.19.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
