#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['autoprop']

package_data = \
{'': ['*']}

install_requires = \
['signature_dispatch~=1.0']

extras_require = \
{':python_version<"3.8"': ['backports.cached-property'],
 'doc': ['sphinx', 'sphinx_rtd_theme', 'autoclasstoc'],
 'test': ['pytest', 'pytest-cov', 'coveralls']}

setup(name='autoprop',
      version='4.0.2',
      description='Infer properties from accessor methods.',
      author='Kale Kundert',
      author_email='kale@thekunderts.net',
      url='https://github.com/kalekundert/autoprop',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='~=3.6',
     )
