
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-16T18:59:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "74104b8c0189698a5c9c3b9549626e5701029071",
 "version": "2.0b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
