
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T17:38:28-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ca70e3e2cec85fead10cb8e6ef5e098eeb6f686",
 "version": "2.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
