info = {"message": "[fix] [lsf] Infinite loop of tools actions (#1474)", "commit": "8915db991f0da7d7078e80185651a7d4a22a83a3", "date": "2021-09-17 15:34:11 +0300", "branch": "release/1.3", "version": "1.2.0+98.g8915db99"}

# This file is automatically generated by version.py
# Do not include it to git!
