
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T12:24:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c9e90eaabf099d1ba4db155de31c4f555cb7a0f",
 "version": "v11.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
