[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=2,<3"]


[tool.flit.metadata]
author = "Russell Smiley"
author-email = "im.russell.smiley@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.rst"
home-page = "https://gitlab.com/ci-cd-devops/build_harness"
module = "build_harness"

requires-python = ">=3.7"

requires = [
    "behave >=1.2.6, <2.0",
    "black >=21.6b0",
    "click >=8.0.1, <9.0",
    "cookiecutter >=1.7.3, <2.0",
    "flake8 >=3.9.2, <4.0",
    "flake8-annotations >=2.6.2, <3.0",
    "flit >=3.2.0, <4.0",
    "gitpython >=3.1.24, <4.0",
    "isort >=5.9.1, <6.0",
    "mypy >=0.910",
    "packaging >=20.9, <21.0",
    "parver >=0.3.1, <1.0",
    "pip >=21.1.3, <22.0",
    "pre_commit >=2.13.0, <3.0",
    "pydantic >=1.8.2, <2.0",
    "pydocstyle >=6.1.1, <7.0",
    "toml >=0.10.2, <1.0",
    "twine >=3.4.1, <4.0",
    "wheel >=0.35.1, <1.0",

    # required for `description-file` parameter above (integration of README.rst)
    "pygments >=2.9.0, <3.0",
]


[tool.flit.scripts]
build-harness = "build_harness.entrypoint:build_harness_entry"
publish-flow = "build_harness.entrypoint:publish_flow_entry"
release-flow = "build_harness.entrypoint:release_flow_entry"


[tool.flit.metadata.requires-extra]
dev = [
    "mutmut >=2.1.0, <3.0",
    "pipenv >=2021.5.29",
    "types-toml >=0.1.3, <1.0",
]
doc = [
    "sphinx >=4.0.2, <5.0",
    "sphinx_rtd_theme >=0.5.2, <1.0",
]
test = [
    "pytest >=6.2.4, <7.0",
    "pytest-cov >=2.12.1, <3.0",
    "pytest-mock >=3.6.1, <4.0",
]


[tool.black]
# templates dir needs to be excluded because it contains .py files
extend-exclude = """
^/build_harness/templates
"""
# Don't forget to sync this with isort, .flake8
line-length = 88


[tool.isort]
extend_skip = ["templates"]
# Don't forget to sync this with black, .flake8
line_length = 88
profile = "black"


[tool.coverage.run]
branch = true
concurrency = ["multiprocessing"]
omit = ["build_harness/templates/*"]
source = ["build_harness"]


[tool.coverage.report]
exclude_lines = [
    "except ImportError",
    "raise NotImplementedError",
    "pass",
    "ABCmeta",
    "abstractmethod",
    "warnings.warn",
]
precision = 0
show_missing = true
