
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T02:04:46-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5aabe4248e1ddb41cb2b594672d2e1643c8eca42",
 "version": "0.1.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
