
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T18:02:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "31c7591403a8f71a863795833c6b06b1bbe10902",
 "version": "1.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
