# Generated by Django 3.2.6 on 2021-09-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_auto_20210910_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailing',
        ),
    ]
