# Generated by Django 3.2.6 on 2021-09-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_delete_policy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailReminder',
        ),
    ]
