info = {"message": "Merge branch 'master' of github.com:heartexlabs/label-studio into release/1.3", "commit": "412f392a8c5bf4041d2de6de41556efc94188449", "date": "2021-09-16 21:28:19 +0300", "branch": "release/1.3", "version": "1.2.0+95.g412f392a"}

# This file is automatically generated by version.py
# Do not include it to git!
