
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T09:53:01+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f655d980900bfc8b593e79d63d47bf59cb2fc10",
 "version": "1.0.7rc8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
