[tool.poetry]
name = "understory-indieauth-server"
version = "0.0.3"
description = "An IndieAuth server for the Understory framework."
authors = ["Angelo Gladding <self@angelogladding.com>"]
license = "CC0-1.0"
readme = "README.md"
packages = [
    { include = "understory" }
]

[tool.poetry.dependencies]
python = "^3.9,<3.10"
understory = "^0.0.71"
indieauth = "^0.0.4"
# indieauth = {path = "/home/angelo/Working/indieauth-python"}

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.3"
flake8 = "^3.9.2"
flake8-docstrings = "^1.6.0"
pep8-naming = "^0.12.1"
radon = "^5.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
