info = {"message": "Fix scaling issues for selection and brush (#1481)", "commit": "1615f1a0707f0ab8383fecc1615a18260a2831bf", "date": "2021-09-18 15:19:53 +0300", "branch": "release/1.3.0.post0", "version": "1.3.0+3.g1615f1a0.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
