[tool.poetry]
name = "qvapay"
version = "v0.2.0"
description = "Python SDK for the QvaPay API"
authors = [
    "Carlos Lugones <contact@lugodev.com>",
    "Ozkar L. Garcell <ozkar.garcell@gmail.com>",
    "Leynier Gutiérrez González <leynier41@gmail.com>"
]
homepage = "https://github.com/lugodev/qvapay-python"
repository = "https://github.com/lugodev/qvapay-python"
documentation = "https://github.com/lugodev/qvapay-python"
readme = "README.md"
license = "MIT"
keywords = ["QvaPay", "api", "payments"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
]

[tool.poetry.urls]
"Tracker" = "https://github.com/lugodev/qvapay-python/issues"

[tool.poetry.dependencies]
python = "^3.8"
httpx = {extras = ["brotli"], version = "^0.19.0"}
python-dateutil = "^2.8.2"
python-dotenv = "^0.19.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
flake8 = "^3.9.2"
black = "^21.8b0"
isort = "^5.9.3"
pytest-cov = "^2.12.1"
pytest-asyncio = "^0.15.1"
commitizen = "^2.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
