# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TSFeatures": "core.ipynb"}

modules = ["core.py"]

doc_url = "https://Nixtla.github.io/fasttsfeatures/"

git_url = "https://github.com/Nixtla/fasttsfeatures/tree/master/"

def custom_doc_links(name): return None
