- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        # NOTE(dtantsur): keep N-3 and older non-voting for these jobs.
        - ironic-standalone
        - ironic-standalone-wallaby
        - ironic-standalone-victoria
        - ironic-standalone-ussuri:
            voting: false
        - ironic-tempest-functional-python3
        - ironic-tempest-functional-python3-wallaby
        - ironic-tempest-functional-python3-victoria
        - ironic-tempest-functional-python3-ussuri:
            voting: false
        - ironic-inspector-tempest
        - ironic-inspector-tempest-wallaby
        - ironic-inspector-tempest-victoria
        - ironic-inspector-tempest-ussuri:
            voting: false
        - ironic-standalone-redfish
        - ironic-standalone-redfish-wallaby:
            voting: false
        - ironic-standalone-redfish-victoria:
            voting: false
        - ironic-standalone-redfish-ussuri:
            voting: false
        # NOTE(dtantsur): these jobs cover rarely changed tests and are quite
        # unstable, so keep them non-voting.
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            voting: false
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-wallaby:
            voting: false
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-victoria:
            voting: false
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode-ussuri:
            voting: false
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-discovery-wallaby:
            voting: false
        - ironic-inspector-tempest-discovery-victoria:
            voting: false
        - ironic-inspector-tempest-discovery-ussuri:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-standalone
        - ironic-standalone-wallaby
        - ironic-standalone-victoria
        - ironic-tempest-functional-python3
        - ironic-tempest-functional-python3-wallaby
        - ironic-tempest-functional-python3-victoria
        - ironic-inspector-tempest
        - ironic-inspector-tempest-wallaby
        - ironic-inspector-tempest-victoria
        - ironic-inspector-tempest-ussuri
        - ironic-standalone-redfish
        - ironic-inspector-tempest-discovery
