[tool.poetry]
name = "drive-utils"
version = "1.0.0"
description = "Useful functions of Google Drive API for python"
authors = ["LucasCiziks <lucas.ciziks@loft.com.br>"]
repository="https://github.com/loft-br/finance-drive-utils"
readme="README.md"

[tool.poetry.dependencies]
python = "^3.7"
oauth2client = "4.1.3"
google-api-python-client = "2.4.0"
pandas = "1.3.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
