title = "Wild Dog configuration file"

[logging]
level = "INFO"
log_file = "wilddog.log"

[database]
url = "postgresql://test:test@localhost:5432/wild_dog"

[api]
secret_key = "super secret"

[server]
host = "0.0.0.0"
port = 50705
threads = 10
scheme = "http"
