
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ecbc42f6b29baba6f4c6c1ba0eee873fab761663",
 "version": "0.1.1.post25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
