[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ['py39']

[flake8]
max-line-length = 100
include = "virgil"
exclude = ["virgil/__init__.py"]

[tool.isort]
profile = "black"
line_length = 100
py_version = 39
skip_gitignore = true
atomic = true
