heat_template_version: newton


description: |
  Creates a Nova server connected to an existing Neutron network and
  optionally assign a floating IP address to server so it is routable from the
  public network.


parameters:

  key_name:
    type: string
    description: Name of keypair to assign to server
    constraints:
    - custom_constraint: nova.keypair

  flavor:
    type: string
    description: Flavor to use for server
    constraints:
    - custom_constraint: nova.flavor

  image:
    type: string
    description: Name of image to use for server

  network:
    type: string
    description: ID of network to which server get connected
    constraints:
    - custom_constraint: neutron.network

  port_security_enabled:
    type: boolean
    description: Whenever port security is enabled on server port
    default: false

  security_groups:
    type: comma_delimited_list
    description: Security groups to subscrive server port
    default: []

  use_extra_dhcp_opts:
    type: boolean
    description: A set of zero or more extra DHCP option pairs
    default: false

  has_floating_ip:
    type: boolean
    description: Whenever server has floating IP associated
    default: false

  floating_network:
    type: string
    description: |
      Public network for which floating IP addresses will be allocated
    constraints:
    - custom_constraint: neutron.network

  scheduler_hints:
    type: json
    description: Hints to create server

  config_drive:
    type: boolean
    description: Whenever server should use config drive with metadata or not
    default: false

  user_data:
    type: string
    default: ''
    description: Optional user_data to be passed to the server

  has_trunk:
    type: boolean
    default: false

  trunk_subport_cidr:
    type: string
    default: ''

  segmentation_type:
    type: string
    description: Segmentation type for trunk subport
    default: ''

  segmentation_id:
    type: number
    description: Segmentation ID for trunk subport
    default: 0

conditions:

  has_floating_ip:
    get_param: has_floating_ip

  use_extra_dhcp_opts:
    get_param: use_extra_dhcp_opts

  has_trunk:
    get_param: has_trunk

resources:

  port:
    type: OS::Neutron::Port
    description: Neutron port
    properties:
      network: {get_param: network}
      port_security_enabled: {get_param: port_security_enabled}
      security_groups: {get_param: security_groups}
      value_specs:
        # TODO(eolivare): I tried a different approach to define
        # extra_dhcp_opts, but it did not work: providing a list of
        # dictionaries from the python class
        # ExtraDhcpOptsCirrosServerStackFixture would have been my preferred
        # option but I got the following error from neutron:
        # No valid key specs matched for: ...
        # Apparently heat does not parse correctly the list of dictionaries and
        # instead it provides a list of strings to neutron
        extra_dhcp_opts:
          if:
            - 'use_extra_dhcp_opts'
            - [{'opt_name': 'domain-name', 'opt_value': '"tobiko.domain"'}]
            - []

  server_name:
    type: OS::Heat::RandomString
    properties:
      character_classes: [{'class': 'lowercase', 'min': 1}]
      length: 8

  server:
    type: OS::Nova::Server
    description: Nova server connected to Neutron port
    properties:
      name: {get_attr: [server_name, value]}
      key_name: {get_param: key_name}
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
        - port: {get_resource: port}
      scheduler_hints: {get_param: scheduler_hints}
      config_drive: {get_param: config_drive}
      user_data_format: RAW
      user_data: {get_param: user_data}

  floating_ip:
    type: OS::Neutron::FloatingIP
    description: Floating IP address to be connected to server
    condition: has_floating_ip
    properties:
      floating_network: {get_param: floating_network}
      port_id: {get_resource: port}

  trunk_subport_network:
    type: OS::Neutron::Net
    condition: has_trunk

  trunk_subport_subnet:
    type: OS::Neutron::Subnet
    condition: has_trunk
    properties:
      network: {get_resource: trunk_subport_network}
      cidr: {get_param: trunk_subport_cidr}

  trunk_subport:
    type: OS::Neutron::Port
    condition: has_trunk
    properties:
      network: {get_resource: trunk_subport_network}
      mac_address: {get_attr: [port, mac_address]}

  trunk:
    type: OS::Neutron::Trunk
    description: Trunk port connected to the server
    condition: has_trunk
    properties:
      port: {get_resource: port}
      sub_ports:
        - {port: {get_resource: trunk_subport},
           segmentation_type: {get_param: segmentation_type},
           segmentation_id: {get_param: segmentation_id}}

outputs:

  fixed_ips:
    description: fixed IP addresses of server
    value: {get_attr: [port, fixed_ips]}

  floating_ip_address:
    description: Floating IP address of server in public network
    value: { get_attr: [ floating_ip, floating_ip_address ] }
    condition: has_floating_ip

  port_security_enabled:
    value: {get_attr: [port, port_security_enabled]}

  security_groups:
    value: {get_attr: [port, security_groups]}

  server_name:
    value: {get_attr: [server, name]}

  server_id:
    value: {get_resource: server}

  port_id:
    value: {get_resource: port}
