
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T16:46:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8bde60564b09b49b4b29c0c990380c111104f93",
 "version": "v0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
