
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T10:42:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3aee378650e3a8180280c8494eb701466326e1f9",
 "version": "2.0.0a13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
