[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 100
py_version = 39
skip_gitignore = true
atomic = true

[tool.pytest]
minversion = "6.0"
addopts = "--cov=virgil"

[tool.coverage.run]
branch = true
source = ["virgil"]
omit = ["src/virgil/__main__.py"]
