
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T13:14:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bff45c81370ac5b2cb7343e22ce69c55ea766a4",
 "version": "21.10.00a+32.g4bff45c"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
