matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=cover
install: pip install -U tox coveralls
language: python
cache: pip
script:
  - tox
after_success: .travis/coveralls.sh
notifications:
  email: false
