
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T14:35:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f6c2e63585430ebfddfd26aeecdb31227ebb6e0",
 "version": "0.12.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
