
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T12:09:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "201770489909fc6dd5fdbf5b03196ecbfc22ca54",
 "version": "5.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
