
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T11:34:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc1b3705732656e764af10682ded6b7cf0b6d260",
 "version": "0.7.1.post.dev44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
