# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['xlsx-lib-infomoto',
 'xlsx-lib-infomoto.xlsx_lib.domain.base_model',
 'xlsx-lib-infomoto.xlsx_lib.domain.electronic',
 'xlsx-lib-infomoto.xlsx_lib.domain.engine',
 'xlsx-lib-infomoto.xlsx_lib.domain.frame',
 'xlsx-lib-infomoto.xlsx_lib.domain.generic_replacements',
 'xlsx-lib-infomoto.xlsx_lib.domain.json_serializable',
 'xlsx-lib-infomoto.xlsx_lib.domain.motorcycle_model',
 'xlsx-lib-infomoto.xlsx_lib.domain.tightening_torques',
 'xlsx-lib-infomoto.xlsx_lib.domain.xlsx_elements',
 'xlsx-lib-infomoto.xlsx_lib.modules']

package_data = \
{'': ['*'],
 'xlsx-lib-infomoto': ['.git/*',
                       '.git/hooks/*',
                       '.git/info/*',
                       '.git/logs/*',
                       '.git/logs/refs/heads/*',
                       '.git/logs/refs/remotes/origin/*',
                       '.git/objects/01/*',
                       '.git/objects/07/*',
                       '.git/objects/09/*',
                       '.git/objects/0b/*',
                       '.git/objects/12/*',
                       '.git/objects/14/*',
                       '.git/objects/15/*',
                       '.git/objects/18/*',
                       '.git/objects/1a/*',
                       '.git/objects/20/*',
                       '.git/objects/25/*',
                       '.git/objects/26/*',
                       '.git/objects/35/*',
                       '.git/objects/36/*',
                       '.git/objects/38/*',
                       '.git/objects/3b/*',
                       '.git/objects/3e/*',
                       '.git/objects/3f/*',
                       '.git/objects/41/*',
                       '.git/objects/49/*',
                       '.git/objects/4c/*',
                       '.git/objects/51/*',
                       '.git/objects/53/*',
                       '.git/objects/57/*',
                       '.git/objects/59/*',
                       '.git/objects/5a/*',
                       '.git/objects/63/*',
                       '.git/objects/69/*',
                       '.git/objects/6c/*',
                       '.git/objects/6f/*',
                       '.git/objects/70/*',
                       '.git/objects/79/*',
                       '.git/objects/7d/*',
                       '.git/objects/80/*',
                       '.git/objects/83/*',
                       '.git/objects/8e/*',
                       '.git/objects/8f/*',
                       '.git/objects/90/*',
                       '.git/objects/93/*',
                       '.git/objects/95/*',
                       '.git/objects/9b/*',
                       '.git/objects/a1/*',
                       '.git/objects/a4/*',
                       '.git/objects/a6/*',
                       '.git/objects/ae/*',
                       '.git/objects/af/*',
                       '.git/objects/b0/*',
                       '.git/objects/b1/*',
                       '.git/objects/b4/*',
                       '.git/objects/b7/*',
                       '.git/objects/bb/*',
                       '.git/objects/bd/*',
                       '.git/objects/c1/*',
                       '.git/objects/c3/*',
                       '.git/objects/c6/*',
                       '.git/objects/c8/*',
                       '.git/objects/ca/*',
                       '.git/objects/cb/*',
                       '.git/objects/ce/*',
                       '.git/objects/cf/*',
                       '.git/objects/d5/*',
                       '.git/objects/db/*',
                       '.git/objects/e0/*',
                       '.git/objects/e1/*',
                       '.git/objects/e3/*',
                       '.git/objects/e6/*',
                       '.git/objects/ec/*',
                       '.git/objects/f3/*',
                       '.git/objects/f4/*',
                       '.git/objects/fc/*',
                       '.git/objects/ff/*',
                       '.git/refs/heads/*',
                       '.git/refs/remotes/origin/*',
                       'dist/*',
                       'xlsx_lib/files/*',
                       'xlsx_lib/files/CBR 250 R ´11/*',
                       'xlsx_lib/files/CBR 250 R ´11/FORZA 125 ´15/*',
                       'xlsx_lib/json/681/*']}

install_requires = \
['openpyxl-image-loader>=1.0.5,<2.0.0',
 'openpyxl>=3.0.7,<4.0.0',
 'pydantic>=1.8.2,<2.0.0']

setup_kwargs = {
    'name': 'xlsx-lib-infomoto',
    'version': '0.1.8',
    'description': '',
    'long_description': None,
    'author': 'tomasdarioam',
    'author_email': 'tomasdarioam@protonmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
