
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T14:39:35-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0714e52c1ce1f500f9bd88320b4e22da2689e45a",
 "version": "2021.09.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
