[build-system]
requires = ["jupyter_packaging~=0.10,<2",
	 "jupyterlab~=3.1",
	 "black",
	 "types-requests",
	 "mypy"
]
build-backend = "jupyter_packaging.build_api"

[tool.jupyter-packaging.options]
skip-if-exists = ["rsp_jupyter_extensions/labextension/static/style.js"]
ensured-targets = ["rsp_jupyter_extensions/labextension/static/style.js", "rsp_jupyter_extensions/labextension/package.json"]

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-packaging.build-args]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.check-manifest]
ignore = ["rsp_jupyter_extensions/labextension/**", "yarn.lock", ".*", "package-lock.json"]
