[tool.poetry]
name = "pycommandparse"
version = "0.2.0"
description = """A collection of classes that help parse commands."""
authors = ["thelegendbeacon"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.6"


[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
