
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-16T17:16:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e07422deedeb0fdeffadc379c4a9d1bd508e3b0",
 "version": "0.13.0rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
