
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T16:31:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "be626fd725f79c6c21249344bf5ff2b23b2e7dc8",
 "version": "v0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
