
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-19T19:28:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c0936069210447923594770847dc5d45c2b7861",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
