
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T17:58:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c63bb71ba8e0c25333abba5e760a7457411dbc73",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
