
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T01:01:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb3e31be08c6ed1492b2c1f6c00cb10a363f831c",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
