---
compute:
  settings:
    default_compute: burst_ec2

  configurations:
    burst_ec2:
      provider: EC2
      access: A...R
      region: us-west-2
      default_image: ami-ubuntu-18.04-1.16.0-00-1569343567
      default_vmtype: t2.medium
      default_gpu_image: Deep Learning AMI (Ubuntu 18.04) Version 36.0
      default_gpu_vmtype: g4dn.xlarge
      disksize: 175
      settings: # Everything AWS-specific goes here
        secret: U...F

storage:
  settings:
    default_storage: burst_s3

  configurations:
    burst_s3:
      provider: AWS
      type: s3
      settings:  #AWS-specific
        access_key_id: A...R
        region: us-west-2
        env_auth: false
        acl: private
        secret_access_key: U...F
