# -*- coding: utf-8 -*-
"""run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cNYubNQ-MCgLwHpM7a6P-5QY8V6RGjN1
"""
#%%
# pip install -i https://test.pypi.org/simple/ slot-filling-ZC==0.1.6
# from slot_ZC import Bi_model
import Bi_model

#%%
#prepare the dataset and split
Bi_model.read_slot(raw_data_path='admin.json',ratio=0.7)

#%%
#divide into training and test set
#%%
#train
train_file = "/content/drive/MyDrive/slot-filling/Bi-Model-Intent-And-Slot/data/train_dev"
test_file = "/content/drive/MyDrive/slot-filling/Bi-Model-Intent-And-Slot/data/test"
vocab_intent_file = "/content/drive/MyDrive/slot-filling/Bi-Model-Intent-And-Slot/data/vocab.intent"
vocab_slot_file = "/content/drive/MyDrive/slot-filling/Bi-Model-Intent-And-Slot/data/vocab.slot"

Bi_model.train(train_file,test_file,vocab_intent_file,vocab_slot_file)

#%%
#predict
Bi_model.predict(sentence="find nonstop flights from salt lake city to new york on saturday april ninth.",
                 data_path="/Users/chenzichu/Desktop/slot-filling/package/slot_ZC")

#%%
Bi_model.fine_tune(train_file = "data/train_dev",
                   test_file = "data/test",
                   vocab_intent_file = "data/vocab.intent",
                   vocab_slot_file = "data/vocab.slot",
                   slot_model_path="model_slot_best.pt",
                   intent_model_path="model_intent_best.pt",
                   total_epoch = 10
              )
# %%

model=Bi_model.ModelClient(model_path="/Users/chenzichu/Desktop/slot-filling/package/slot_ZC/model")
model.predict(sentence="find nonstop flights from salt lake city to new york on saturday april ninth.")

# %%
