# @package _group_
_target_: pytorch.recipes.vision.GAN.models.infogan.Discriminator
n_classes: ${module.generator.n_classes}
code_dim: ${module.generator.code_dim}
img_size: ${module.generator.img_size}
channels: ${module.generator.channels}
