[tool.poetry]
name = "pytest-watcher"
version = "0.1.0"
description = ""
authors = ["olzhasar <o.arystanov@gmail.com>"]

[tool.poetry.scripts]
pytest_watcher = "pytest_watcher:run"

[tool.poetry.dependencies]
python = "^3.9"
inotify = "^0.2.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
black = "^21.9b0"
mypy = "^0.910"
isort = "^5.9.3"
pytest-mock = "^3.6.1"
freezegun = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
