
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T09:28:38-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1d9d05d7beb4ba819653f62e47da48a4c4ffd25",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
