# This file is part of the Exact program
#
# Copyright (c) 2021 Jo Devriendt, KU Leuven
#
# Exact is distributed under the terms of the MIT License.
# You should have received a copy of the MIT License along with Exact.
# See the file LICENSE.

[tool.poetry]
name = "exact"
version = "0.4.0"
description = "A Python interface to the Exact integer linear programming solver"
authors = ["Jo Devriendt"]
license = "MIT License"
readme = "README.md"
homepage = "https://gitlab.com/JoD/exact"
repository = "https://gitlab.com/JoD/exact"
include = ["exact/libExact.so","exact/headers/**/*.hpp"]

classifiers=[
    'Development Status :: 1 - Planning',
    'License :: OSI Approved :: MIT License',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3',
]

[tool.poetry.dependencies]
python = "^3.7"
cppyy = "^2.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

