
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T12:30:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7febcd209cdeb5e769a6d8a6985b82167b406d76",
 "version": "0.13.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
