
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T09:30:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e2f13b3857411c782f5d51cc518ccee07647b4b",
 "version": "1.8.4-dev.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
