site_name: ticktack for Radiocarbon Box Modelling
nav:
    - Home: index.md
    - 'Fitting a Carbon Box Model':
        - fitting-with-mcmc: notebooks/fitting.ipynb
        - fitting-with-cps:  notebooks/01_Injection_Recovery_ControlPoints.ipynb
    - Box API Docs: box_api.md
    - Flow API Docs: flow_api.md
    - CarbonBoxModel API Docs: cbm_api.md
    - CarbonFitter API Docs: cf_api.md

theme:
  name: "material"
repo_url: https://github.com/SharmaLlama/ticktack
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates