
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T09:45:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c5158f7be6c7594ea5f15dbacf36f717a2cdabb",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
