
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T16:03:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9962328ca3b08b24d28a512dcb939a3c95910f6b",
 "version": "0.4.72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
