
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T23:48:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7047ecd4b900336ca1ca0ff9a937d7b1ab2900cf",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
