# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: baguasys/bagua:latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
        python -m pip install --pre git+https://github.com/BaguaSys/bagua-core.git
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Test with pytest
      run: |
        pytest
