
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T20:23:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7583617bb62a19b6611dcd08ccb77b1312fff74a",
 "version": "0.3.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
