
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T18:27:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d0bf2bc1ced84b831fa76453030a6e9c04a1b85",
 "version": "2021.09.15post0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
