# Generated by Django 3.1.7 on 2021-08-28 19:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprintPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('imprint_data', wagtail.core.fields.StreamField([('imprint_data', wagtail.core.blocks.StructBlock([('tax_id', wagtail.core.blocks.CharBlock(help_text='Add your Tax ID', required=True)), ('company_authority', wagtail.core.blocks.CharBlock(help_text='Company Authority', required=True)), ('non_warranty', wagtail.core.blocks.CharBlock(help_text='Add your non warranty', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Add additional description', required=False))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Imprint Page',
                'verbose_name_plural': 'Imprint Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
