
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T12:56:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "51f0dca1212e70e9fd8a852796d9f3b659fa50ab",
 "version": "1.6.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
