repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "8c2e6113ec9f1b3013544e26c0943456befb07bf"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/hakancelik96/unimport
  #   rev: 2875c033c00877b6797f3a05761c7c7fe9aae46c
  #   hooks:
  #     - id: unimport
  #       args: [--remove, --include-star-import]
  - repo: https://github.com/pycqa/isort
    rev: "bf9398ea0fed45ad1cd2899b8fd1d1c15190f025"
    hooks:
      - id: isort
        files: "gdsfactory/.*"
        args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: 2b2f0c74acdb3de316e23ceb7dd0d7945c354050
  #   hooks:
  #     - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: "8a59528c2d8ae1ef5f366039c728614aaf1a470b"
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "26f7dca77a937964eb85d25e6b331cb1e7b40701"
    hooks:
      - id: flake8
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "214c33306afe17f1cc7d2d55e4da705b6ebe0627"
  #   hooks:
  #     - id: mypy
  #       exclude: ^(docs/|example-plugin/|tests/fixtures)
  #       additional_dependencies:
  #         - "pydantic"

  # - repo: https://github.com/terrencepreilly/darglint
  #   rev: master
  #   hooks:
  #       - id: darglint
  #
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: ""
  #   hooks:
  #       - id: pydocstyle
