
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T03:17:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fba1655bc1e4a52a7acae4bd6b452c233a9c04ec",
 "version": "0.1.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
