
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T15:22:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "438cbed9d2235575f558d9c1d2cc4cc3ee0a34b8",
 "version": "2.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
