# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: cc292cf
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: tooling
project_email: dummy@dummy.dummy
project_name: copier_python_dummy
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.9'
tooling_tracking_repo: true
year_of_project_creation: 2021
