#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['copier_python_dummy']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['fire~=0.4']

setup(name='copier_python_dummy',
      version='0.0.1',
      description='Short description of your project.',
      author=None,
      author_email='Blake Naccarato <dummy@dummy.dummy>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      python_requires='>=3.9',
     )
