
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T10:29:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1a37b9d3cd533d17b7a3c53c975e3ab86ebdb37",
 "version": "0.0.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
