[build-system]
requires = [
  "setuptools>=19.6",
  # see https://github.com/numpy/numpy/pull/18389
  "wheel>=0.36.2",

  # cython version is imposed by that of numpy, see release notes
  # https://github.com/numpy/numpy/releases/tag/v1.19.2
  # Cython 3.0 is the next version after 0.29, and a major change,
  # we forbid it until we can properly test against it
  "Cython>=0.29.21,<3.0; python_version>='3.7'",
  "oldest-supported-numpy",
]
