
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T10:03:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f28e4b8ddbcd8a41d8aa1cc6bafad4f4c1f31bcb",
 "version": "0.3.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
