[tool.poetry]
name = "canvas-cli"
version = "1.3.4"
description = "A command-line tool for the Canvas Medical EMR system."
authors = ["Beau Gunderson <beaugunderson@github-username.x>", "Stephen Mitchell <scuml@github-username.x>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"
requests = "^2.26.0"
arrow = "^1.1.1"
python-decouple = "^3.4"
cached-property = "^1.5.2"
memoization = "^0.4.0"

[tool.poetry.dev-dependencies]
djangorestframework = "^3.12.4"
django-memoize = "^2.3.1"
stringcase = "^1.2.0"
bpython = "^0.21"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
canvas-cli = 'canvas_cli.canvas_cli:cli'
