
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T11:15:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1811ea696c3b7c46f12e4512144b5ee58ac1ae9",
 "version": "v1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
