
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-22T19:28:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ec00a25a07c45a55d8e182c86fe3a2e005e13e4",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
