
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T09:31:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5873c0f6b9c588b1d5f0ecbca2f1a637cd70377",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
