[tool.poetry]
name = "convert_to_queryset"
version = "0.1.1"
description = ""
authors = ["deepak <info.deepakpatidar@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
