# @package _group_
- channel_name: "modality_1"
  encoder_args:
    _target_: faim.encoder.non_temporal.text.DoCNNEncoder
    channel_name: "modality_1"
    conv_filters: [[1, 32], [2, 32], [3, 32], [4, 64], [5, 64]]
    mlp_sizes: [256, 128]
- channel_name: "modality_2"
  encoder_args:
    _target_: faim.encoder.non_temporal.dense.MLPEncoder
    channel_name: "modality_2"
    input_dim: 256
    mlp_dims: [128]
