
ATYP_DOMAINNAME = 3
ATYP_IPV4 = 1
ATYP_IPV6 = 6

CMD_CONNECT = 1
CMD_BIND = 2
CMD_UDP_ASSOCIATE = 3

REPCODE_SUCCESS = 0
REPCODE_SERVER_ERROR = 1
REPCODE_FORBIDDEN = 2
REPCODE_NETWORK_NOT_AVALIBE = 3
REPCODE_HOST_NOT_AVALIBE = 4
REPCODE_CONNREFUSHED = 5
REPCODE_TTL_ERROR = 6
REPCODE_CMD_NOT_SUPPORTED = 7
REPCODE_ADDRESS_NOT_SUPPORTED = 8

AUTHMETHOD_NOAUTH = 0
AUTHMETHOD_USERNAME_PASSWD = 2
AUTHMETHOD_GSSAPI = 1
AUTHMETHOD_NOT_AVALIBE = 0xff