
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T12:21:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcf6e6d34ddaab8a016a856dedb06ea475ffe55b",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
