
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T19:58:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f63d715ce20c726fb6509549305a770ee8d1c878",
 "version": "0.3.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
