
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T14:01:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3a93908d2abeeee445e15880e7bec8212007aa0",
 "version": "2021.09.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
