# @package _group_
_target_: pytorch.recipes.graph.torchgraph.datamodule.csv_module.CSVDataModule
nodes_content_file: data/citeseer-content.csv
edges_list_file: data/citeseer.edgelist.csv
undirected_graph: true
