
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2021-09-22T00:30:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4642715a24e9ec0005e1cc2b144cbec03c4de48",
 "version": "1.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
