
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-21T01:20:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a94637e3822cdd33f187168157e5a9bdb08dffa",
 "version": "0.1.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
