# Generated by Django 3.2.6 on 2021-09-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailreminder')),
            ],
        ),
    ]
