# Generated by Django 3.2.6 on 2021-09-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_delete_useremailing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
