# Generated by Django 3.2.6 on 2021-09-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0017_emailreminder_modules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
