
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-09T13:13:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d9de6785ad837c3eee1cfbb578388251f824622",
 "version": "0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
