[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "argparse>=1.4.0",
    "requests>=2.25.1",
    "pyyaml>=5.4.1"
]
build-backend = "setuptools.build_meta"
[tool.black]
line-length = 88
target-version = ['py39']
include = '\.py$'
#extend-exclude = ''
