[tool.poetry]
name = "colorframe"
version = "0.2.1"
description = "Python utility to add borders to my photography pictures"
authors = ["Felix Soubelet <felix.soubelet@protonmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/fsoubelet/toychain"

[tool.poetry.dependencies]
python = "^3.6"
joblib = "^1.0"
loguru = "^0.5.1"
Pillow = "^8.3.2"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
typer-cli = "^0.0.11"

[tool.poetry.scripts]
colorframe = "colorframe.__main__:app"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
