
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T12:05:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9795a7b769ee56fda029245f699a910f53291f8f",
 "version": "4.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
