info = {"message": "Update DM build", "commit": "35b15f1741de8a8336befc12603241eee5812540", "date": "2021-09-17 16:45:48 +0300", "branch": "release/1.3", "version": "1.2.0+99.g35b15f17.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
