
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-15T17:28:21+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3eacea9cacc3647aa4409cfd1a4a04887315543",
 "version": "1.0.7rc9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
