[tool.poetry]
name = "gnista-cli"
version = "0.1.4"
description = "A CLI client to access gnista.io"
authors = ["Markus Hoffmann"]
license = "MIT"

readme = "README.md"
homepage = "https://gnista.io"
repository = "https://gitlab.com/campfiresolutions/public/gnista.io-cli.git"

include = ["LICENSE.md"]

[tool.poetry.dependencies]
python = "^3.9"
gnista-library = "1.0.10"
structlog = "^21.1.0"
argparse = "^1.4.0"
elevate = "^0.1.3"

[tool.poetry.dev-dependencies]
pyinstaller = "^4.5.1"
visplorepy = {path = "lib/visplorepy-1.2.0-py3-none-any.whl"}
black = "^21.8b0"
flake8 = "^3.9.2"
pylint = "^2.10.2"
mypy = "^0.910"
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
