
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-20T22:40:14+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "847e1d8eb97818174bbee4ce02e820743c1702e3",
 "version": "3.7.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
