[tool.poetry]
name = "ardlib"
version = "0.1.0"
description = "ardlib"
authors = ["musangtara <musangtara@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
